# OpenAPI/Swagger UI configuration for the dev profile
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# Swagger UI OAuth2 client
springdoc.swagger-ui.oauth.client-id=swagger-ui
springdoc.swagger-ui.oauth.use-pkce-with-authorization-code-grant=true
