package com.pallas.storyservice.data;

import static org.assertj.core.api.Assertions.assertThat;

import com.pallas.storyservice.domain.SharedWith;
import com.pallas.storyservice.domain.Story;
import java.time.OffsetDateTime;
import java.util.Optional;
import java.util.UUID;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.test.context.ActiveProfiles;

/**
 * Integration tests for persistence layer (JpaStoryAdapter and database).
 *
 * <p>Tests the actual persistence of Story entities to the database, catching Hibernate entity
 * mapping issues and database constraint violations. This layer is separate from the API layer to
 * isolate persistence concerns.
 *
 * <p>Uses {@code @DataJpaTest} which loads only the persistence layer without the full application
 * context, providing faster test execution and clearer error messages.
 */
@DataJpaTest
@ActiveProfiles("test")
@DisplayName("Story Persistence Integration Tests")
class JpaStoryAdapterIntegrationTest {

  @Autowired private StoryRepository repository;

  private JpaStoryAdapter adapter;

  private static final UUID AUTHOR_ID = UUID.fromString("550e8400-e29b-41d4-a716-446655440001");

  @BeforeEach
  void setUp() {
    adapter = new JpaStoryAdapter(repository);
    repository.deleteAll();
  }

  // =========================================================================
  // Story Persistence Tests
  // =========================================================================

  @Test
  @DisplayName("JpaStoryAdapter.save() should persist story with explicitly generated UUID")
  void testSaveWithExplicitUuidDoesNotTriggerUpdateAsInsert() {
    // Arrange - Create a domain story with explicit UUID (not generated by DB)
    UUID storyId = UUID.randomUUID();
    String contentJson = "[{\"insert\":\"Test story\"}]";
    OffsetDateTime now = OffsetDateTime.now();
    Story domain = new Story(storyId, AUTHOR_ID, contentJson, SharedWith.TRUSTED, now);

    // Act - Save to database
    Story saved = adapter.save(domain);

    // Assert - Verify story was persisted (not attempted UPDATE which fails)
    assertThat(saved.getId()).isEqualTo(storyId);
    assertThat(repository.findById(storyId)).isPresent();
  }

  @Test
  @DisplayName(
      "JpaStoryAdapter.save() should persist publishedAt even though column is marked updatable=false")
  void testSavePreservesPublishedAtTimestamp() {
    // Arrange
    UUID storyId = UUID.randomUUID();
    String contentJson = "[{\"insert\":\"Timestamped story\"}]";
    OffsetDateTime publishedAt = OffsetDateTime.now();
    Story domain = new Story(storyId, AUTHOR_ID, contentJson, SharedWith.COMMUNITY, publishedAt);

    // Act - Save to database
    Story saved = adapter.save(domain);

    // Assert - Verify publishedAt was persisted correctly
    assertThat(saved.getPublishedAt()).isNotNull();
    var entity = repository.findById(storyId).orElseThrow();
    assertThat(entity.getPublishedAt()).isEqualTo(publishedAt);
  }

  @Test
  @DisplayName("Story entities should have unique IDs across multiple saves")
  void testMultipleStoriesHaveUniqueIds() {
    // Arrange & Act
    UUID id1 = UUID.randomUUID();
    UUID id2 = UUID.randomUUID();

    Story story1 =
        new Story(
            id1, AUTHOR_ID, "[{\"insert\":\"Story 1\"}]", SharedWith.TRUSTED, OffsetDateTime.now());
    Story story2 =
        new Story(
            id2, AUTHOR_ID, "[{\"insert\":\"Story 2\"}]", SharedWith.PUBLIC, OffsetDateTime.now());

    adapter.save(story1);
    adapter.save(story2);

    // Assert
    assertThat(repository.count()).isEqualTo(2L);
    assertThat(repository.findById(id1)).isPresent();
    assertThat(repository.findById(id2)).isPresent();
  }

  @Test
  @DisplayName("JpaStoryAdapter.findById() should retrieve and convert entity back to domain")
  void testFindByIdRetrievesAndConvertsDomain() {
    // Arrange - Save a story first
    UUID storyId = UUID.randomUUID();
    String contentJson = "[{\"insert\":\"Find me\"}]";
    OffsetDateTime publishedAt = OffsetDateTime.now();
    Story original = new Story(storyId, AUTHOR_ID, contentJson, SharedWith.CONNECTED, publishedAt);
    adapter.save(original);

    // Act - Retrieve by ID
    Optional<Story> retrieved = adapter.findById(storyId);

    // Assert - Verify domain object is reconstructed correctly
    assertThat(retrieved).isPresent();
    assertThat(retrieved.get().getId()).isEqualTo(storyId);
    assertThat(retrieved.get().getAuthorId()).isEqualTo(AUTHOR_ID);
    assertThat(retrieved.get().getContent()).isEqualTo(contentJson);
    assertThat(retrieved.get().getSharedWith()).isEqualTo(SharedWith.CONNECTED);
    assertThat(retrieved.get().getPublishedAt()).isEqualTo(publishedAt);
  }

  @Test
  @DisplayName("JpaStoryAdapter.findById() should return empty Optional for non-existent story")
  void testFindByIdReturnsEmptyForMissing() {
    // Arrange
    UUID nonExistentId = UUID.randomUUID();

    // Act
    Optional<Story> result = adapter.findById(nonExistentId);

    // Assert
    assertThat(result).isEmpty();
  }

  @Test
  @DisplayName(
      "Story content JSON should survive serialization/deserialization cycle through database")
  void testContentJsonRoundTripThroughDatabase() {
    // Arrange - Complex Quill Delta format content
    UUID storyId = UUID.randomUUID();
    String complexContent =
        "[{\"insert\":\"Bold\",\"attributes\":{\"bold\":true}},{\"insert\":\" and \"},{\"insert\":\"italic\",\"attributes\":{\"italic\":true}}]";
    Story domain =
        new Story(storyId, AUTHOR_ID, complexContent, SharedWith.PUBLIC, OffsetDateTime.now());

    // Act
    adapter.save(domain);
    Optional<Story> retrieved = adapter.findById(storyId);

    // Assert - Content should be preserved exactly
    assertThat(retrieved).isPresent();
    assertThat(retrieved.get().getContent()).isEqualTo(complexContent);
  }

  @Test
  @DisplayName("Story entity should respect all SharedWith enum values")
  void testAllSharedWithValuesCanBePersisted() {
    UUID baseId = UUID.randomUUID();

    for (SharedWith level : SharedWith.values()) {
      // Arrange
      UUID storyId =
          new UUID(
              baseId.getMostSignificantBits(), baseId.getLeastSignificantBits() + level.ordinal());
      Story domain =
          new Story(storyId, AUTHOR_ID, "[{\"insert\":\"Story\"}]", level, OffsetDateTime.now());

      // Act
      Story saved = adapter.save(domain);

      // Assert
      assertThat(saved.getSharedWith()).isEqualTo(level);
      var entity = repository.findById(storyId).orElseThrow();
      assertThat(entity.getSharedWith().toString()).isEqualTo(level.toString());
    }
  }

  @Test
  @DisplayName("Story authorId should be immutable after persistence")
  void testAuthorIdIsImmutableInDatabase() {
    // Arrange - Save a story with an author
    UUID storyId = UUID.randomUUID();
    Story original =
        new Story(
            storyId,
            AUTHOR_ID,
            "[{\"insert\":\"Original author\"}]",
            SharedWith.TRUSTED,
            OffsetDateTime.now());
    adapter.save(original);

    // Act - Try to retrieve (should have original author)
    Optional<Story> retrieved = adapter.findById(storyId);

    // Assert - Author should be the original one
    assertThat(retrieved).isPresent();
    assertThat(retrieved.get().getAuthorId()).isEqualTo(AUTHOR_ID);
  }
}
