analyzer:
  language:
    strict-inference: true
    strict-raw-types: true
    strict-casts: false
  exclude:
    - test/*.dart
  errors:
    deprecated_member_use_from_same_package: ignore
    unused_import: ignore
    uri_does_not_exist: ignore
    undefined_class: ignore
    undefined_method: ignore
    undefined_identifier: ignore
    non_type_as_type_argument: ignore
    cast_to_non_type: ignore
    const_with_non_constant_argument: ignore
    non_constant_list_element: ignore
